In [ ]:
import tensorflow as tf
import pathlib

In [ ]:
daily_sales_numbers=[21,22,-31,100,45,-1,99]

In [ ]:
tf_data_set=tf.data.Dataset.from_tensor_slices(daily_sales_numbers)

In [ ]:
for sales in tf_data_set.as_numpy_iterator():
  print(sales)

21
22
-31
100
45
-1
99


In [ ]:
for sales in tf_data_set.take(3):
  print(sales.numpy())

21
22
-31


In [ ]:
filteres_data_set=tf_data_set.filter(lambda x: x>0)

In [ ]:
for sales in filteres_data_set:
  print(sales.numpy())

21
22
100
45
99


In [ ]:
mapped=_data_set=filteres_data_set.map(lambda x: x*72)

In [ ]:
for sales in mapped:
  print(sales.numpy())

1512
1584
7200
3240
7128


In [ ]:
for sales in mapped.batch(2):
  print(sales.numpy())

[1512 1584]
[7200 3240]
[7128]


In [ ]:
for sales in mapped.shuffle(2):
  print(sales.numpy())

1512
1584
7200
3240
7128


In [ ]:
tf_dataset=tf.data.Dataset.from_tensor_slices(daily_sales_numbers)

In [ ]:
tf_processed_element=tf_dataset.filter(lambda x :x>0).map(lambda y:y*72).shuffle(2).batch(2)

In [ ]:
for sales in tf_processed_element:
  print(sales.numpy())

[1512 1584]
[3240 7128]
[7200]


In [ ]:
dataset_url= "https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz"

In [ ]:
dataset_flower=tf.keras.utils.get_file("flower_photos",dataset_url,untar=True,cache_dir=".")

228813984/228813984 [==============================] - 2s 0us/step


In [ ]:
dataset_flower

'./datasets/flower_photos'

In [ ]:
flower_data_set_path=pathlib.Path(dataset_flower)

In [ ]:
roses=list(flower_data_set_path.glob("roses/*"))
tulips=list(flower_data_set_path.glob("tulips/*"))

In [ ]:
images=tf.data.Dataset.list_files(f"{str(flower_data_set_path)}/*/*",shuffle=False)

In [ ]:
for img in images.take(5):
  print(img.numpy())

b'datasets/flower_photos/daisy/100080576_f52e8ee070_n.jpg'
b'datasets/flower_photos/daisy/10140303196_b88d3d6cec.jpg'
b'datasets/flower_photos/daisy/10172379554_b296050f82_n.jpg'
b'datasets/flower_photos/daisy/10172567486_2748826a8b.jpg'
b'datasets/flower_photos/daisy/10172636503_21bededa75_n.jpg'


In [ ]:
imges_shuffled=images.shuffle(200)
for img in imges_shuffled.take(5):
  print(img.numpy())

b'datasets/flower_photos/daisy/10466558316_a7198b87e2.jpg'
b'datasets/flower_photos/daisy/11439894966_dca877f0cd.jpg'
b'datasets/flower_photos/daisy/11023272144_fce94401f2_m.jpg'
b'datasets/flower_photos/daisy/14507818175_05219b051c_m.jpg'
b'datasets/flower_photos/daisy/14167543177_cd36b54ac6_n.jpg'


In [ ]:
images_count=len(imges_shuffled)

In [ ]:
images_count

3670

In [ ]:
train_size=int(images_count*0.8)

In [ ]:
train_ds=imges_shuffled.take(train_size)
test_ds=imges_shuffled.skip(train_size)

In [ ]:
len(train_ds)

2936

In [ ]:
len(test_ds)

734

In [ ]:
def get_label(file_path):
  import os
  return tf.strings.split(file_path,os.path.sep)[2]

In [ ]:
for label in train_ds.map(get_label).take(5):
  print(label.numpy())

b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'


In [ ]:
def process_img(file_path):
  label=get_label(file_path)
  img=tf.io.read_file(file_path)
  img=tf.image.decode_jpeg(img)
  img=tf.image.resize(img,[128,128])
  return img,label

In [ ]:
for img,label in train_ds.map(process_img).take(2):
  print(img,label.numpy())

tf.Tensor(
[[[230.58301 235.33301 244.08301]
  [232.5     234.75    242.     ]
  [233.50098 236.50098 241.50098]
  ...
  [205.58301 203.58301 206.58301]
  [200.58203 198.58203 203.08203]
  [202.08105 200.08105 205.08105]]

 [[231.49707 236.99414 243.00488]
  [232.5     234.75    242.     ]
  [232.0039  235.0039  240.0039 ]
  ...
  [207.74219 205.74219 208.74219]
  [204.23828 202.23828 207.23633]
  [207.23438 205.23438 210.23438]]

 [[232.5     238.16504 242.67969]
  [234.16016 236.66016 241.66016]
  [232.74512 235.74512 240.74512]
  ...
  [207.91504 207.16992 211.40527]
  [207.40527 206.40527 211.40527]
  [209.91016 208.91016 214.91016]]

 ...

 [[191.59473 193.59473 190.59473]
  [192.33984 194.33984 191.50977]
  [193.33984 195.33984 194.33984]
  ...
  [  0.        0.        0.     ]
  [  0.        0.        0.     ]
  [  0.        0.        0.     ]]

 [[194.00781 196.00781 193.00586]
  [195.00781 197.00781 196.00781]
  [195.00781 197.00781 196.00781]
  ...
  [  0.        0.        0.

In [ ]:
train_ds=train_ds.map(process_img)

In [ ]:
def scale(img,label):
  return img/255,label

In [ ]:
train_ds_scale=train_ds.map(scale)

In [ ]:
for image,label in train_ds_scale.take(5):
  print(image[0][0])
  print(label)

tf.Tensor([0.17598039 0.22640932 0.15710784], shape=(3,), dtype=float32)
tf.Tensor(b'daisy', shape=(), dtype=string)
tf.Tensor([0.27110142 0.43367034 0.21897978], shape=(3,), dtype=float32)
tf.Tensor(b'daisy', shape=(), dtype=string)
tf.Tensor([0.8541054  0.87371325 0.85018384], shape=(3,), dtype=float32)
tf.Tensor(b'daisy', shape=(), dtype=string)
tf.Tensor([0.24443933 0.2875766  0.15424326], shape=(3,), dtype=float32)
tf.Tensor(b'daisy', shape=(), dtype=string)
tf.Tensor([0.2143842  0.37909007 0.09673713], shape=(3,), dtype=float32)
tf.Tensor(b'daisy', shape=(), dtype=string)
